language: c
compiler:
    - gcc
    - clang

install:
  - git clone --quiet --depth=100 "https://github.com/nanomsg/nanomsg.git" ~/builds/nanomsg
      && pushd ~/builds/nanomsg
      && ./autogen.sh
      && ./configure
      && make 
      && sudo make install
      && popd;
script: make all

